// Package v1alpha1 defines the miniMesh CRD API types.
//
// Two custom resources are provided:
//   - MeshPolicy – controls mTLS enforcement for a set of workloads.
//   - MeshCertificate – requests a short-lived service certificate managed by
//     the in-cluster CA.
package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"sigs.k8s.io/controller-runtime/pkg/scheme"
)

// GroupVersion is the API group/version for miniMesh resources.
var GroupVersion = schema.GroupVersion{Group: "mesh.minimesh.io", Version: "v1alpha1"}

var (
	// SchemeBuilder registers the types with the scheme.
	SchemeBuilder = &scheme.Builder{GroupVersion: GroupVersion}
	// AddToScheme is a shorthand for SchemeBuilder.AddToScheme.
	AddToScheme = SchemeBuilder.AddToScheme
)

// ─────────────────────────────────────────────────────────────────────────────
// MeshPolicy
// ─────────────────────────────────────────────────────────────────────────────

// MeshPolicySpec configures mTLS mode and an optional workload selector.
type MeshPolicySpec struct {
	// MTLSMode is one of STRICT, PERMISSIVE, or DISABLE.
	// +kubebuilder:validation:Enum=STRICT;PERMISSIVE;DISABLE
	// +kubebuilder:default=STRICT
	MTLSMode string `json:"mtlsMode,omitempty"`
	// Selector restricts the policy to pods with matching labels.
	// An empty selector matches all pods in the namespace.
	Selector map[string]string `json:"selector,omitempty"`
}

// MeshPolicyStatus reflects the reconciliation result.
type MeshPolicyStatus struct {
	Ready bool   `json:"ready"`
	Phase string `json:"phase,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="MTLSMode",type=string,JSONPath=`.spec.mtlsMode`
// +kubebuilder:printcolumn:name="Ready",type=boolean,JSONPath=`.status.ready`

// MeshPolicy configures mTLS and mesh policies for a set of workloads.
type MeshPolicy struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              MeshPolicySpec   `json:"spec,omitempty"`
	Status            MeshPolicyStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// MeshPolicyList contains a list of MeshPolicy.
type MeshPolicyList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []MeshPolicy `json:"items"`
}

// ─────────────────────────────────────────────────────────────────────────────
// MeshCertificate
// ─────────────────────────────────────────────────────────────────────────────

// MeshCertificateSpec requests a certificate for a Kubernetes service.
type MeshCertificateSpec struct {
	// ServiceName is the name of the Kubernetes Service.
	ServiceName string `json:"serviceName"`
	// Namespace is the namespace of the service.
	Namespace string `json:"namespace"`
	// TTL is the requested certificate lifetime (default 24h).
	// +kubebuilder:default="24h"
	TTL string `json:"ttl,omitempty"`
}

// MeshCertificateStatus records the generated secret reference and expiry.
type MeshCertificateStatus struct {
	// CertSecretRef is the name of the TLS Secret created in spec.namespace.
	CertSecretRef string `json:"certSecretRef,omitempty"`
	ExpiresAt     string `json:"expiresAt,omitempty"`
	Ready         bool   `json:"ready"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Service",type=string,JSONPath=`.spec.serviceName`
// +kubebuilder:printcolumn:name="Ready",type=boolean,JSONPath=`.status.ready`
// +kubebuilder:printcolumn:name="Expires",type=string,JSONPath=`.status.expiresAt`

// MeshCertificate represents a managed mTLS certificate for a mesh service.
type MeshCertificate struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              MeshCertificateSpec   `json:"spec,omitempty"`
	Status            MeshCertificateStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// MeshCertificateList contains a list of MeshCertificate.
type MeshCertificateList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []MeshCertificate `json:"items"`
}

// ─────────────────────────────────────────────────────────────────────────────
// Scheme registration
// ─────────────────────────────────────────────────────────────────────────────

func init() {
	SchemeBuilder.Register(&MeshPolicy{}, &MeshPolicyList{})
	SchemeBuilder.Register(&MeshCertificate{}, &MeshCertificateList{})
}

// ─────────────────────────────────────────────────────────────────────────────
// DeepCopy implementations (normally generated by controller-gen)
// ─────────────────────────────────────────────────────────────────────────────

func (in *MeshPolicy) DeepCopyObject() runtime.Object        { return in.DeepCopy() }
func (in *MeshPolicyList) DeepCopyObject() runtime.Object    { return in.DeepCopy() }
func (in *MeshCertificate) DeepCopyObject() runtime.Object   { return in.DeepCopy() }
func (in *MeshCertificateList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

func (in *MeshPolicy) DeepCopy() *MeshPolicy {
	if in == nil {
		return nil
	}
	out := *in
	if in.Spec.Selector != nil {
		out.Spec.Selector = make(map[string]string, len(in.Spec.Selector))
		for k, v := range in.Spec.Selector {
			out.Spec.Selector[k] = v
		}
	}
	return &out
}

func (in *MeshPolicyList) DeepCopy() *MeshPolicyList {
	if in == nil {
		return nil
	}
	out := *in
	out.Items = make([]MeshPolicy, len(in.Items))
	for i := range in.Items {
		out.Items[i] = *in.Items[i].DeepCopy()
	}
	return &out
}

func (in *MeshCertificate) DeepCopy() *MeshCertificate {
	if in == nil {
		return nil
	}
	out := *in
	return &out
}

func (in *MeshCertificateList) DeepCopy() *MeshCertificateList {
	if in == nil {
		return nil
	}
	out := *in
	out.Items = make([]MeshCertificate, len(in.Items))
	for i := range in.Items {
		out.Items[i] = *in.Items[i].DeepCopy()
	}
	return &out
}
